compile : CondalMarcoJoanPau-T7.o
	cc CondalMarcoJoanPau-T7.o -o CondalMarcoJoanPau-T7.exe -lm
	rm CondalMarcoJoanPau-T7.o

CondalMacoJoanPau-T7.o : CondalMarcoJoanPau-T7.c
	cc -c -ansi -Wall -g CondalMarcoJoanPau.c