compilar : CondalMarcoJoanPau-T8E.o
	cc CondalMarcoJoanPau-T8E.o -o CondalMarcoJoanPau-T8E.exe -lm
	rm CondalMarcoJoanPau-T8E.o

CondalMarcoJoanPau-T8E.o : CondalMarcoJoanPau-T8E.c
	cc -c -ansi -Wall -g CondalMarcoJoanPau-T8E.c